package ru.geekbrains.gb_kotlin.data.errors

class NoAuthException : Throwable(){
}